WIP: nuke generate_session_file.py
it even doesn't exist for this bot File generate_session_file.py, line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Signed-off-by: HafizZiq <hafizuddinismail552@gmail.com>